spring:
  profiles:
    active: dev

server:
  servlet:
    context-path: /market/api

---
spring:
  profiles: dev
  datasource:
 #   driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/market-place
    username: admin
    password: secret
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8082



---
spring:
  profiles: prod
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

server:
  port: ${PORT}
